owner: bitforge
repo: yago_status_page

sites:
  - name: Yago Page
    url: https://yago.cloud
    icon: https://raw.githubusercontent.com/bitforge/yago_status_page/master/assets/yago-parrot-circle.svg
  - name: Yago App
    url: https://app.yago.cloud
    icon: https://raw.githubusercontent.com/bitforge/yago_status_page/master/assets/yago-parrot-circle.svg
  - name: Yago API
    url: https://yago.cloud/api/health
    icon: https://raw.githubusercontent.com/bitforge/yago_status_page/master/assets/yago-parrot-circle.svg

status-website:
  theme: light
  cname: status.yago.cloud
  favicon: https://raw.githubusercontent.com/bitforge/yago_status_page/master/assets/yago-parrot-circle.png
  faviconSvg: https://raw.githubusercontent.com/bitforge/yago_status_page/master/assets/yago-parrot-circle.svg
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Yago Status Page
  navbar:
    - title: Yago
      href: https://yago.cloud
    - title: Yago App
      href: https://app.yago.cloud
    - title: Yago API
      href: https://yago.cloud/api/doc